# netlify.toml

[build]
  # Comando para construir el proyecto
  command = "npm run build"

  # Directorio donde se encuentran los archivos est치ticos generados
  publish = "dist" # Cambia esto si tu directorio de salida es diferente

# Configuraci칩n de redirecciones (opcional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Configuraci칩n de funciones (opcional)
[functions]
  directory = "functions" # Cambia esto si tienes funciones serverless en una carpeta diferente

# Variables de entorno (opcional)
[build.environment]
  NODE_VERSION = "14" # Especifica la versi칩n de Node.js si es necesario
